// Shared between client and server: just the provider identities, no SDKs.
export const PROVIDERS = [
  "openai",
  "anthropic",
  "google",
  "xai",
  "mistral",
  "deepseek",
  "groq",
  "cerebras",
  "togetherai",
  "fireworks",
  "deepinfra",
  "cohere",
  "perplexity",
  "baseten",
  "gateway",
  "openrouter",
  "moonshotai",
  "zai",
  "alibaba",
  "minimax",
  "nvidia",
  "sambanova",
  "nebius",
  "huggingface",
] as const;
export type ProviderId = (typeof PROVIDERS)[number];

export const PROVIDER_LABELS: Record<ProviderId, string> = {
  openai: "OpenAI",
  anthropic: "Anthropic",
  google: "Google Gemini",
  xai: "xAI Grok",
  mistral: "Mistral",
  deepseek: "DeepSeek",
  groq: "Groq",
  cerebras: "Cerebras",
  togetherai: "Together AI",
  fireworks: "Fireworks AI",
  deepinfra: "DeepInfra",
  cohere: "Cohere",
  perplexity: "Perplexity",
  baseten: "Baseten",
  gateway: "Vercel AI Gateway",
  openrouter: "OpenRouter",
  moonshotai: "Moonshot AI (Kimi)",
  zai: "Z.AI (Zhipu GLM)",
  alibaba: "Alibaba Qwen",
  minimax: "MiniMax",
  nvidia: "NVIDIA NIM",
  sambanova: "SambaNova",
  nebius: "Nebius",
  huggingface: "Hugging Face",
};
